### ISSUE TITLE
Update NLog 5 to release version

### ISSUE THREAD

**Issue by chris-peterson** [chris-peterson/Spiffy#14]
Currently on latest (`5.0.0-beta11`).  Shadowing their version numbering until it is released.

**Comment by snakefoot** [comment]
NLog ver 4.5 will be the next official version. Supporting NetStandard1.5 and NetStandard2.0

**Comment by chris-peterson** [comment]
Done!
https://www.nuget.org/packages/Spiffy.Monitoring.NLog/4.5.0
