### ISSUE TITLE
Splunk wants comma separted field in quotes.

### ISSUE THREAD

**Issue by azuwish** [chris-peterson/Spiffy#16]
It looks like only the *Message* field surrounds the value with double quotes. That can be a problem on multi-value fields in splunk.

For example
```context["ImportantStuff"] = string.Join(",", arrayOfGoodies) ;```

For splunk, I have to change this to
```context["ImportantStuff"] = "\"" + string.Join(",", arrayOfGoodies) + "\"";```

Don't forget NOT to add quotes if they're already there.

Sorry I couldn't do this myself.

**Comment by azuwish** [comment]
This is not an issue if you put a space after the comma.
```context["ImportantStuff"] = string.Join(", ", arrayOfGoodies);```

**Comment by chris-peterson** [comment]
Re-opening as I don't want consumers to need to put `, ` if they only want `,`

**Comment by chris-peterson** [comment]
Fixed in 839c0258ad38c9f7f5d2d849b75759b7e224704c
