### ISSUE TITLE
NLog.Config file ignored

### ISSUE THREAD

**Issue by ebelew** [chris-peterson/Spiffy#5]
I created an NLog.config file for an app, but it is completely ignored. The only way to configure spiffy appears to be the `Initialize(Action<NLogConfigurationApi>)` method.

**Comment by chris-peterson** [comment]
This is by design as I prefer fluent configuration in code.

I'd be open to a `NLogConfigurationApi.UseConfigFile(PATH_TO_CONFIG_FILE)` semantic.
